name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: MiSTer FPGA

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: arm-linux-musleabihf-gcc -std=c99 -D_XOPEN_SOURCE=700 -static -O2 -o mbc ../mbc.c ||die
    - name: make smaller
      run: arm-linux-musleabihf-strip mbc ||die

